"""Notification adapters for pushing monitoring results.

Supported channels: WeChat Work Bot, Feishu Bot, DingTalk Bot, Email (SMTP).
"""

from __future__ import annotations

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any

import httpx

logger = logging.getLogger(__name__)

_WEBHOOK_TIMEOUT = 15.0


async def _post_webhook(url: str, payload: dict[str, Any]) -> bool:
    try:
        async with httpx.AsyncClient(timeout=_WEBHOOK_TIMEOUT) as client:
            resp = await client.post(url, json=payload)
            resp.raise_for_status()
            return True
    except httpx.HTTPError as e:
        logger.warning("Webhook POST failed to %s: %s", url[:60], e)
        return False


def _format_report(title: str, papers: list[dict[str, Any]]) -> str:
    lines = [
        f"## {title} - Weekly Paper Digest",
        f"Found **{len(papers)}** new papers:\n",
    ]
    for i, p in enumerate(papers, 1):
        authors = p.get("authors", [])
        first_author = authors[0] if authors else "?"
        et_al = " et al." if len(authors) > 1 else ""
        year = p.get("year", "?")
        venue = p.get("venue", "") or ""
        lines.append(
            f"{i}. **{p.get('title', 'Untitled')}** -- "
            f"{first_author}{et_al}, {year}"
        )
        if venue:
            lines.append(f"   *{venue}*")
        doi = p.get("doi")
        if doi:
            lines.append(f"   https://doi.org/{doi}")
        lines.append("")
    return "\n".join(lines)


async def send_wechat(
    webhook_url: str, topic_name: str, papers: list[dict[str, Any]]
) -> bool:
    content = _format_report(topic_name, papers)
    payload = {"msgtype": "markdown", "markdown": {"content": content}}
    return await _post_webhook(webhook_url, payload)


async def send_feishu(
    webhook_url: str, topic_name: str, papers: list[dict[str, Any]]
) -> bool:
    elements: list[dict[str, Any]] = [
        {
            "tag": "markdown",
            "content": (
                f"**{topic_name}** -- Weekly Digest\n"
                f"Found **{len(papers)}** new papers."
            ),
        }
    ]
    for i, p in enumerate(papers[:20], 1):
        authors = p.get("authors", [])
        first_author = authors[0] if authors else "?"
        et_al = " et al." if len(authors) > 1 else ""
        year = p.get("year", "?")
        doi = p.get("doi", "")
        line = (
            f"{i}. {p.get('title', 'Untitled')} - "
            f"{first_author}{et_al} ({year})"
        )
        if doi:
            line += f"\n  [{doi}](https://doi.org/{doi})"
        elements.append({"tag": "markdown", "content": line})

    payload = {
        "msg_type": "interactive",
        "card": {
            "header": {
                "title": {"tag": "plain_text", "content": "Paper Expert Monitor"},
                "template": "blue",
            },
            "elements": elements,
        },
    }
    return await _post_webhook(webhook_url, payload)


async def send_dingtalk(
    webhook_url: str, topic_name: str, papers: list[dict[str, Any]]
) -> bool:
    content = _format_report(topic_name, papers)
    if len(content) > 20000:
        content = content[:19900] + "\n\n... (truncated)"
    payload = {
        "msgtype": "markdown",
        "markdown": {"title": f"{topic_name} - Paper Digest", "text": content},
    }
    return await _post_webhook(webhook_url, payload)


def _format_email_html(title: str, papers: list[dict[str, Any]]) -> str:
    rows: list[str] = []
    for i, p in enumerate(papers, 1):
        authors = p.get("authors", [])
        first_author = authors[0] if authors else "?"
        et_al = " et al." if len(authors) > 1 else ""
        year = p.get("year", "?")
        venue = p.get("venue", "") or ""
        doi = p.get("doi", "")
        title_link = (
            f'<a href="https://doi.org/{doi}">{p.get("title", "Untitled")}</a>'
            if doi
            else p.get("title", "Untitled")
        )
        row = f'<tr><td style="padding:8px 0;border-bottom:1px solid #eee">{i}.</td>'
        row += f'<td style="padding:8px 0;border-bottom:1px solid #eee"><b>{title_link}</b><br>'
        row += f'<span style="color:#666">{first_author}{et_al}, {year}</span>'
        if venue:
            row += f' · <em>{venue}</em>'
        row += "</td></tr>"
        rows.append(row)

    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"></head>
<body style="font-family:Arial,sans-serif;max-width:700px;margin:0 auto">
<h2 style="color:#2c3e50">{title} - Weekly Paper Digest</h2>
<p>Found <b>{len(papers)}</b> new papers this week:</p>
<table style="width:100%;border-collapse:collapse">
{"".join(rows)}
</table>
<p style="color:#95a5a6;font-size:12px;margin-top:20px">
  Generated by <a href="https://github.com/anomalyco/paper_expert">Paper Expert</a>
</p>
</body></html>"""
    return html


async def send_email(config: Any, topic_name: str, papers: list[dict[str, Any]]) -> bool:
    notify = config.notify
    if not notify.smtp_host or not notify.email_recipient:
        logger.warning("Email not configured (missing smtp_host or email_recipient)")
        return False

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"[Paper Expert] {topic_name} - Weekly Digest ({len(papers)} papers)"
        msg["From"] = notify.smtp_username or notify.email_recipient
        msg["To"] = notify.email_recipient

        text_content = _format_report(topic_name, papers)
        html_content = _format_email_html(topic_name, papers)
        msg.attach(MIMEText(text_content, "plain", "utf-8"))
        msg.attach(MIMEText(html_content, "html", "utf-8"))

        def _send():
            if notify.smtp_port == 465:
                server = smtplib.SMTP_SSL(notify.smtp_host, notify.smtp_port, timeout=15)
            else:
                server = smtplib.SMTP(notify.smtp_host, notify.smtp_port, timeout=15)
            if notify.smtp_username and notify.smtp_password:
                server.starttls()
                server.login(notify.smtp_username, notify.smtp_password)
            server.send_message(msg)
            server.quit()

        import asyncio
        await asyncio.to_thread(_send)
        logger.info("Email sent to %s", notify.email_recipient)
        return True
    except Exception as e:
        logger.warning("Email send failed: %s", e)
        return False


async def send_all(
    config: Any,  # PaperExpertConfig
    topic_name: str,
    papers: list[dict[str, Any]],
    channels: list[str] | None = None,
) -> dict[str, bool]:
    notify = config.notify
    results: dict[str, bool] = {}

    targets: dict[str, str] = {}
    if notify.wechat_webhook:
        targets["wechat"] = notify.wechat_webhook
    if notify.feishu_webhook:
        targets["feishu"] = notify.feishu_webhook
    if notify.dingtalk_webhook:
        targets["dingtalk"] = notify.dingtalk_webhook
    if notify.smtp_host and notify.email_recipient:
        targets["email"] = ""  # email uses config directly, not a webhook url

    if channels:
        targets = {k: v for k, v in targets.items() if k in channels}

    for channel_name in list(targets):
        if channel_name == "wechat":
            results[channel_name] = await send_wechat(
                targets[channel_name], topic_name, papers
            )
        elif channel_name == "feishu":
            results[channel_name] = await send_feishu(
                targets[channel_name], topic_name, papers
            )
        elif channel_name == "dingtalk":
            results[channel_name] = await send_dingtalk(
                targets[channel_name], topic_name, papers
            )
        elif channel_name == "email":
            results[channel_name] = await send_email(config, topic_name, papers)

    return results
